### ISSUE TITLE
includeSS

### ISSUE THREAD

**Issue by anniehsp** [fochlac/mui-feedback-dialog#1]
Hi! I'm trying to use mui-feedback-dialog for my feedback in react webpage and it works really fine!

but there was one thing I want to do with this amazing library which is automatically check "Attach Screenshot" checkbox, and I saw your source and it doesn't provide condition of that.

So I was wondering if you could add additional props for that option! Thanks for reading and will be waiting for your response! :)

**Comment by fochlac** [comment]
I added the prop `attachScreenshotOnOpen`. Please have a try and see if everything works :)

**Comment by anniehsp** [comment]
it works really well! Thank you so much! :)
