### ISSUE TITLE
You need to enable Javascript to run this app

### ISSUE THREAD

**Issue by RylanSchaeffer** [fochlac/mui-feedback-dialog#3]
I have a problem that emerges in Chrome but not Firefox. Specifically, there's a warning label that says "You need to enable Javascript to run this app." Screenshot below:

![image](https://user-images.githubusercontent.com/8942987/171297562-e12d906e-dde6-4e9d-ac91-c128ee0847c4.png)

Do you know what causes this or how to fix it?

**Comment by fochlac** [comment]
I had a look, I assume you tried it in a code-sandbox with the useScreencapture prop set to false (default).
Codesandbox includes a noscript-tag in its iframe that is propably picked up by the `dom-to-image`-lib used for serializing the underlying html. 
![image](https://user-images.githubusercontent.com/19147668/171319665-1c869ef5-9e89-4bc0-bc10-572305f5e58c.png)

If you need a very exact copy of what the user is seeing you can set the `useScreencapture`-prop to true. Unfortunatly that will open the screen-share prompt and is not very intuitive and user-friendly, but it will capture exactly what the user is seeing.

**Comment by chasebrignac** [comment]
Thank you that did technically fix the issue! We don't like how useScreencapture to true opens a dialog box that asks for permission to screen record. Is this our only option to get it working in chrome?

<img width="1680" alt="Screen Shot 2022-06-01 at 9 13 16 AM" src="https://user-images.githubusercontent.com/7634554/171451061-bf2a4fd8-4e3e-40b3-b9ea-6cc9bc8a0a73.png">

**Comment by RylanSchaeffer** [comment]
~~Chiming in, I don't think that flag `useScreencapture` is the answer. The above problem (`You need to enable Javascript to run this app`) occurs in Chrome, not Firefox. I think something else is amiss~~

Edit: I misunderstood your message. Yes, I think Chase's question is the right one: is there another solution that doesn't require setting `useScreencapture` to true?

**Comment by RylanSchaeffer** [comment]
I'm unclear why the problem appears on Chrome, but not Firefox?

**Comment by chasebrignac** [comment]
@fochlac when we set the useScreencapture to true this doesn't work on chrome mobile (takes a picture with the camera instead of a screenshot) and in chrome on mac it asks the user to open all kinds of permission dialogs. So we want to get `dom-to-image` lib working on chrome somehow. Right now it seems to be broken.

<img width="1560" alt="Screen Shot 2022-06-01 at 10 40 51 AM" src="https://user-images.githubusercontent.com/7634554/171468859-1890fabc-b6dd-4eef-84cf-1fde88910533.png">

**Comment by fochlac** [comment]
I guess this is part of how dom-to-image resolves your html-structure. I expect the library has some different handling based on the different behaviour of the browser. You could try to add something like `Array.from(document.querySelectorAll('noscript')).forEach(elem => elem.style.display = 'none')` to your main-app-file to explicitly set some style for the noscript tags.

If this doesn't help I need some more insight into your actual application, all input from my side are blind guesses at the moment. ^^

**Comment by chasebrignac** [comment]
We are happy to add you to our repos. It's a pretty cool app and we hope you will like when it is done! I'll also try what you suggested now.

**Comment by RylanSchaeffer** [comment]
We'll try your solution, and if it doesn't work, we'll share the code with you?

**Comment by RylanSchaeffer** [comment]
Thanks for being willing to help us, by the way!
